version: '3.5'
services:
  floatie: 
    image: lucasegp/floatie:latest
    hostname: floatie
    expose:
      - "8080" # HTTP service port
      - "9999" # raft protocol gRPC port

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - floatie
    ports:
      - "8080:8080"
