version: '3.5'
services:
  floatie-1: &floatie
    image: lucasegp/floatie:latest
    expose:
      - "8080" # HTTP service port
      - "9999" # raft protocol gRPC port
    command: "--id=1"
    volumes:
      - ./floatie.json:/srv/floatie.json

  floatie-2:
    <<: *floatie
    command: "--id=2"

  floatie-3:
    <<: *floatie
    command: "--id=3"

  floatie-4:
    <<: *floatie
    command: "--id=4"

  floatie-5:
    <<: *floatie
    command: "--id=5"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - floatie-1
      - floatie-2
      - floatie-3
      - floatie-4
      - floatie-5
    ports:
      - "8080:8080"
